name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: [self-hosted, linux]  # Run this job on the Raspberry Pi self-hosted runner

    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/serviceAccountKey.json  # Set the environment variable for the service account JSON file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code from the repository
        
      - name: Set up Google Cloud authentication
        run: |
          # Create the service account JSON file from the GitHub secret
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > $GOOGLE_APPLICATION_CREDENTIALS
          

      - name: Debug authentication
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS
          cat $GOOGLE_APPLICATION_CREDENTIALS
          ls -l $GOOGLE_APPLICATION_CREDENTIALS

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
        
      - name: Lint the code
        run: |
          pylint --disable=all --enable=error main.py  # Lint the code and ignore warnings

      - name: Restart script service
        run: |
          sudo systemctl restart my_script.service

      # - name: Run the project
      #   run: |
      #     python3 main.py $GOOGLE_APPLICATION_CREDENTIALS  # Replace with your script to run the project
           
      - name: Clean up
        run: |
          nohup python3 main.py &  # Run the new instance of main.py in the background